# Generated by Django 3.2.7 on 2021-09-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('category_desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ec_category',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.IntegerField(null=True)),
                ('invoice_no', models.IntegerField(null=True, unique=True)),
                ('payment_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ec_order',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, null=True, unique=True)),
                ('product_desc', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('sub_category_id', models.IntegerField()),
                ('specification', models.CharField(default='', max_length=255)),
                ('Image', models.ImageField(upload_to='')),
                ('stock', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('discount_price', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ec_products',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('verified_email', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('verified_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(default='', max_length=10)),
                ('role', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ec_users',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategory_desc', models.CharField(max_length=255)),
                ('parent_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'db_table': 'ec_subcategory',
            },
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_status', models.CharField(max_length=100)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('shipment_date', models.DateTimeField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orders')),
            ],
            options={
                'db_table': 'ec_order_tracking',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
    ]
