# Generated by Django 3.2.7 on 2021-09-29 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Category name must be in letters')])),
                ('category_desc', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'ec_category',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ec_login',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('invoice_no', models.CharField(max_length=256)),
                ('payment_address', models.TextField()),
                ('shipping_address', models.TextField()),
            ],
            options={
                'db_table': 'ec_order',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Firstname must be in Character')])),
                ('last_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Lastname must be in Character')])),
                ('email', models.EmailField(max_length=254)),
                ('verified_email', models.BooleanField(default=False)),
                ('mobile_no', models.BigIntegerField(validators=[django.core.validators.RegexValidator('^([0-9]{10})$', message='mobile no must have 10 digit')])),
                ('verified_mobile_no', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(?=.*[!$?])(?=.*[a-z])(?=.*[A-Z]).{8}$', message='invalid password.Password must be 8 characters.and atleast 1 numeric and symbols')])),
                ('role', models.CharField(default='guest', max_length=20, validators=[django.core.validators.RegexValidator("^[a-zA-Z -.\\'\\_]+$", message='Role must be in Character')])),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'ec_users',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='SubCategory name must be in  letters')])),
                ('subcategory_desc', models.CharField(default='', max_length=255)),
                ('parent_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'db_table': 'ec_subcategory',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', message='Product name must be in Alpha numeric')])),
                ('product_desc', models.CharField(default='', max_length=255)),
                ('specification', models.CharField(default='', max_length=255)),
                ('Image', models.FileField(upload_to='images/')),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('brand', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', message='Brand name must be in Alpha numeric')])),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcategory')),
            ],
            options={
                'db_table': 'ec_products',
            },
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_status', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Status must be in Letters')])),
                ('current_location', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Current Location must be in Letters')])),
                ('destination', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Destination must be in Letters')])),
                ('shipment_date', models.DateTimeField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orders')),
            ],
            options={
                'db_table': 'ec_order_tracking',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'ec_customers',
            },
        ),
    ]
