# Generated by Django 3.2.7 on 2021-09-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210920_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=255),
        ),
    ]
