# Generated by Django 3.2.7 on 2021-10-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customers_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='ec_customers',
        ),
    ]
