# Generated by Django 3.2.7 on 2021-10-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customers_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='is_active',
        ),
    ]
