# Generated by Django 3.2.7 on 2021-09-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210922_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
