# Generated by Django 3.2.7 on 2021-09-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210922_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='invoice_no',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.TextField(),
        ),
    ]
