# Generated by Django 3.2.7 on 2021-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210922_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='destination',
            field=models.CharField(max_length=255),
        ),
    ]
