# Generated by Django 3.2.7 on 2021-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_ordertracking_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='current_location',
            field=models.CharField(max_length=255),
        ),
    ]
