# Generated by Django 3.2.7 on 2021-09-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_no',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
