# Generated by Django 3.2.7 on 2021-09-23 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_users_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator("^[a-zA-Z -.\\'\\_]+$", message='User name must be in Character')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
