# Generated by Django 3.2.7 on 2021-09-23 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210923_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator("^[a-zA-Z -.\\'\\_]+$", message='Firstname must be in Character')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator("^[a-zA-Z -.\\'\\_]+$", message='Lastname must be in Character')]),
        ),
    ]
