# Generated by Django 3.2.7 on 2021-09-23 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210923_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_no',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator('^([0-9]{10})$', message='mobile no must have 10 digit')]),
        ),
    ]
