# Generated by Django 3.2.7 on 2021-09-23 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_users_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator("^[a-zA-Z -.\\'\\_]+$", message='Role must be in Character')]),
        ),
    ]
