# Generated by Django 3.2.7 on 2021-09-23 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(?=.*[!$?])(?=.*[a-z])(?=.*[A-Z]).{8}$', message='invalid password.Password must be 8 characters.and atleast 1 numeric and symbols')]),
        ),
    ]
