# Generated by Django 3.2.7 on 2021-09-23 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_users_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Firstname must be in Character')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='guest', max_length=20, null=True, validators=[django.core.validators.RegexValidator("^[a-zA-Z -.\\'\\_]+$", message='Role must be in Character')]),
        ),
    ]
