# Generated by Django 3.2.7 on 2021-09-23 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210923_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='guest', max_length=20, validators=[django.core.validators.RegexValidator("^[a-zA-Z -.\\'\\_]+$", message='Role must be in Character')]),
        ),
    ]
