# Generated by Django 3.2.7 on 2021-09-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210923_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
