# Generated by Django 3.2.7 on 2021-09-23 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20210923_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator("^[a-zA-Z-.'\\_]*$", message='Category name must be in letters')]),
        ),
    ]
