# Generated by Django 3.2.7 on 2021-09-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_usertable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertable',
            table='ec_usertable',
        ),
    ]
