# Generated by Django 3.2.7 on 2021-09-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_usertable_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usertable',
        ),
    ]
