# Generated by Django 3.2.7 on 2021-09-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20210927_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
